config/routes.rb
Buymore::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items

  resources :carts

  get "store/index"
  resources :products

  root 'store#index', as: 'store'

  

end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>Emere Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Emere Bookshelf" %>
  </div>
  <div id="columns">
    <div id="side">
<!-- START_HIGHLIGHT -->
      <!-- START:hidden_div -->
      <%if @cart%>
      	<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
       	 <%= render @cart %>
       	<% end %>
      <% end %>
    <!-- END:hidden_div -->

<!-- END_HIGHLIGHT -->
      <ul>
        <li><%= link_to 'Home',   store_path   %></li>
      </ul>
    <% unless session[:user_id] %>
      <ul>
	  	<li><%= link_to 'Signup',   'users#new'   %></li>
	  	<li><"\n" > </li>
	    <li><%= link_to 'Login',   'login'   %></li>
	  <ul>	
	<% end %>
      
      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete   %>
      <% end %>
      
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>